server:
  port: 2202

spring:
  application:
    name: seata-storage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: '0407'
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
#使用此配置代替registry.conf来配置seata的注册中心，告诉seata client 怎么去访问seata server
seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848 #seata server 所在的nacos服务地址
      application: seata-server #seata server 的服务名称、默认就是seata-server 没有改可以不配
      username: nacos
      password: nacos
      group: SEATA_GROUP #seata server 所在组 默认就是SEATA_GROUP 没有改可以不配
  config:
    #配置seata的配置中心，可以读取关于seata client的一写配置
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.alibaba.domain
  configuration:
    map-underscore-to-camel-case: true


